---
- block:
    - name: Create containers
      lxc_container:
        name: "baseline_{{ item.base }}"
        state: stopped
        clone_name: "{{ item.name }}"
        clone_snapshot: True
        backing_store: overlayfs
      loop: "{{ containers }}"

    - name: Start containers
      lxc_container:
        name: "{{ item.name }}"
        state: started
      with_items: "{{ containers }}"

    - name: Wait for container networking (10s)
      wait_for:
        timeout: 10

    - name: Obtain container IPs
      lxc_container:
        name: "{{ item.name }}"
      with_items: "{{ containers }}"
      register: container_info

    - name: Add entry to hosts file
      lineinfile:
        line: "{{ item.lxc_container.ips[0] + ' ' + item.lxc_container.name }}"
        path: /etc/hosts
        insertafter: EOF
      with_items: "{{ container_info.results }}"

    - name: Bootstrap python on ubuntu
      raw: apt install -y python
      delegate_to: "{{ item.name }}"
      remote_user: root
      when: 
        - "'ubuntu' in item.base"
      loop: "{{ containers }}"

    - name: Add {{ user }} 
      user:
        name: "{{ user }}"
        state: present
        shell: /bin/bash
      delegate_to: "{{ item.name }}"
      remote_user: root
      loop: "{{ containers }}"

    - name: Authorized key for {{ user }}
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', auth_key) }}"
      delegate_to: "{{ item.name }}"
      remote_user: root
      loop: "{{ containers }}"

    - name: Ensure sudo is installed
      package:
        name: sudo
        state: present
      delegate_to: "{{ item.name }}"
      remote_user: root
      loop: "{{ containers }}"

    - name: Add {{ user }} to sudoers
      copy:
        dest: /etc/sudoers.d/{{ user }}_sudo
        content: "{{ user }} ALL = (ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: 0400
      delegate_to: "{{ item.name }}"
      remote_user: root
      loop: "{{ containers }}"
  tags:
    - setup
